# Generated by Django 2.1.2 on 2018-10-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plsql_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=1000)),
                ('Answer', models.TextField(max_length=10000)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
